name: CI — Lint, Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: messaging_test
      DB_USER: root
      DB_PASS: root
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/messaging_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/messaging_app/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        for i in {1..60}; do
          mysqladmin ping -h 127.0.0.1 -uroot -proot >/dev/null 2>&1 && break
          echo "MySQL not ready yet ($i/60)..."
          sleep 1
        done
        mysqladmin ping -h 127.0.0.1 -uroot -proot

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./messaging_app
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt || true
        fi
        # test tools + linting + coverage
        pip install pytest pytest-cov pytest-django mysqlclient flake8 coverage || true
        # fallback: install PyMySQL in case mysqlclient fails to build on runner
        pip install pymysql || true

    - name: Lint (flake8)
      working-directory: ./messaging_app
      run: |
        echo "Running flake8..."
        # Run flake8 on the Django package and fail if any issues exist
        # Adjust target directory if your python package lives elsewhere
        flake8 messaging_app

    - name: (Optional) Run migrations
      working-directory: ./messaging_app
      run: |
        python manage.py migrate --noinput || true

    - name: Run tests with pytest + coverage
      working-directory: ./messaging_app
      run: |
        # produce junit xml and coverage reports
        pytest --maxfail=1 --disable-warnings --junitxml=report.xml --cov=messaging_app --cov-report=xml:coverage.xml --cov-report=html:coverage_html || true

    - name: Upload JUnit test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: messaging_app/report.xml

    - name: Upload coverage xml
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: messaging_app/coverage.xml

    - name: Upload coverage HTML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: messaging_app/coverage_html

    - name: Upload pytest cache (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-cache
        path: messaging_app/.pytest_cache || messaging_app/report.xml
