name: Build & Push Docker image

# Run on pushes to main and allow manual trigger
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.abrahamezekiel }}
          password: ${{ secrets.__Ab4Christ@__@ }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          push: true
          tags: |
            ${{ secrets.abrahamezekiel }}/messaging-app:${{ github.sha }}
            ${{ secrets.abrahamezekiel }}/messaging-app:latest
          # optional: enable build cache (requires registry or GitHub packages)
          # cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/messaging-app:cache
          # cache-to: type=inline
